services:
  api:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - ccp
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules/

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ccp
    ports:
      - "5432:5432"
    networks:
      - ccp

networks:
  ccp:
    driver: bridge
